<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones.

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.


Therefore if we can determine if the first stage will land, we can determine the cost of a launch.

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [ ]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 17.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp310-cp310-linux_x86_64.whl size=1192328 sha256=c376dd7f2e1852f8984ed2c6faa52a8e2820e329284938a85e36c3f41e6c6175
  Stored in directory: /root/.cache/pip/wheels/8b/6d/9c/e1793e5a2d85b89b8c362a4f0e3def54b786bcd14923b9ff00
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.23
    Uninstalling SQLAlchemy-2.0.23:
      Successfully uninstalled SQLAlchemy-2.0.23
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 0.13.0 requires sqlalchemy<3.0dev,>=1.4, but you have sqlalchemy 1.3.9 which is incompatible.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.
Successfully installed sqlalchemy-1.3.9

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [22]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [23]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [24]:
!pip install -q pandas==1.1.5

In [38]:
%sql ibm_db_sa://gtc27297:YCIikTdcI5gi240Z@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/BLUDB?security=SSL

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/connection.py", line 45, in __init__
    engine = sqlalchemy.create_engine(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 239, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:ibm_db_sa

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
  File "/usr/local/lib/python3.10/dist-packages/sql/connection.py", line 70, in set
    cls.current = existing or Connection(descriptor, connect_args, creator)
  File "/usr/local/lib/python3.10/dist-packages/sql/connection.py", line 45, in __init__
    engine = sqlalchemy.create_engine(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/langhelpers.py", line 239, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:ibm_db_sa

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

In [35]:
%sql sqlite:///my_data1.db

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

In [37]:
%sql sqlite:///my_data1.db

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

In [26]:
import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

101

**Note:This below code is added to remove blank rows from table**

In [27]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [28]:
%sql select distinct Launch_Site from SPACEXTBL

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [29]:
%sql select * from SPACEXTBL Where Launch_Site like "CCA%" limit 5

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

In [30]:
%sql select distinct landing_outcome from SPACEXTBL

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [31]:
%sql select sum(payload_mass_kg_) from SPACEXTBL Where customer = 'NASA (CRS)'

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [34]:
%sql select avg(playload_mass_kg_) from SPACEXTBL where booster_version ='F9 v1,1'

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

In [33]:
# Load the SQL extension and connect to the SQLite database

%sql sqlite:///my_data1.db

# Run the SQL query
result = %sql select avg(playload_mass_kg_) from SPACEXTBL where booster_version ='F9 v1,1'

# Display the result
result

The sql extension is already loaded. To reload it, use:
  %reload_ext sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])
 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [39]:
%sql select min(DATE) from SPACEXTBL WHERE landing__outcome = 'Success (ground pad)'

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [42]:
%sql select booster_version from SPACEXTBL where landing__outcome = 'Success (drone ship)'\
and payload_mass__kg_ between 4000 and 6000

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 7




##### List the total number of successful and failure mission outcomes

In [41]:
%sql select mission_outcome, count(mission_outcome) from SPACEXTBL GROUP BY mission_outcome

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 8



##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [40]:
%sql select booster_version, payload_mass__kg_ from SPACEXTBL\
where payload_mass__kg_ = (select max(payload_mass__kg_) from SPACEXTBL)

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [43]:
%sql select booster_version, launch_site from SPACEXTBL where landing__outcome = 'Failure (drone ship)' and year(DATE) = 2015

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [44]:
%sql select count(landing__outcome), landing__outcome from SPACEXTBL \
where DATE between '2010-06-04' and '2017-03-20' group by landing__outcome\
order by count(landing__outcome) desc

 * sqlite:///my_data1.db
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 203, in execute
    conn.internal_connection.rollback()
AttributeError: 'Connection' object has no attribute 'rollback'

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite:///my_data1.db'])

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>